import { assertInlineSnapshot } from "@std/testing/unstable-snapshot";
import {
  assert,
  assertEquals,
  assertRejects,
  assertStringIncludes,
  assertThrows,
} from "@std/assert";
import { resolve } from "node:path";
import {
  defineCompositeAction,
  defineProject,
  defineWorkflow,
} from "../src/github_actions/mod.ts";
import { scenario } from "../src/testing/mod.ts";
import { generateFiles } from "../src/compiler/generator.ts";
import { lowerProject } from "../src/compiler/authoring.ts";
import { parse } from "../src/deps.ts";
import { TASK_PREPARE_SCRIPT } from "../src/task-runtime/bootstrap.ts";
import { generateV1 } from "../services/type-service/src/github/actions/v1.ts";

Deno.test("composite outputs and nested local calls render into native YAML", async () => {
  const draft = defineCompositeAction("actions/greet/action.yml", {
    name: "Greet",
    description: "Greeting",
    author: "Example",
    branding: { icon: "terminal", color: "blue" },
    inputs: { who: { description: "Recipient", required: true } },
    outputs: { greeting: { description: "Greeting" } },
  });
  const action = draft.steps(({ step }) =>
    step.run({
      id: "greet",
      name: "Greet",
      shell: "bash",
      run: 'echo "greeting=hello" >> "$GITHUB_OUTPUT"\n',
      outputs: ["greeting"],
      env: { WHO: draft.inputs.who },
      if: ({ inputs }) => inputs.who.ne(""),
    }).outputs(({ steps }) => ({ greeting: steps.greet.outputs.greeting }))
  );
  const parent = defineCompositeAction("actions/parent/action.yml", {
    name: "Parent",
    description: "Calls local action",
  }).steps(({ step }) => step.uses(action, { with: { who: "world" } }));
  const workflow = defineWorkflow(".github/workflows/greet.yml", {
    on: { push: {} },
  }).job(
    "greet",
    ({ job }) =>
      job.runsOn("ubuntu-latest").uses(action, {
        id: "greet",
        with: { who: "world" },
      }),
  );
  const files = await generateFiles(
    defineProject({ workflows: [workflow], actions: [action, parent] }),
    "./actions.ts",
    "unused",
  );
  assertEquals(files.map((file) => file.path), [
    ".github/workflows/greet.yml",
    "actions/greet/action.yml",
    "actions/parent/action.yml",
  ]);
  assertInlineSnapshot(
    String(files[0].content),
    `# Generated by Tsugiori from actions.ts
name: .github/workflows/greet.yml
on:
  push: {}
jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - id: greet
        uses: ./actions/greet
        with:
          who: world
`,
    { serializer: (yaml) => yaml },
  );
  assertInlineSnapshot(
    String(files[1].content),
    `# Generated by Tsugiori from actions.ts
name: Greet
description: Greeting
author: Example
branding:
  icon: terminal
  color: blue
inputs:
  who:
    description: Recipient
    required: true
outputs:
  greeting:
    description: Greeting
    value: \${{ steps.greet.outputs.greeting }}
runs:
  using: composite
  steps:
    - name: Greet
      id: greet
      if: \${{ (inputs.who != '') }}
      env:
        WHO: \${{ inputs.who }}
      run: |
        echo "greeting=hello" >> "\$GITHUB_OUTPUT"
      shell: bash
`,
    { serializer: (yaml) => yaml },
  );
  assertInlineSnapshot(
    String(files[2].content),
    `# Generated by Tsugiori from actions.ts
name: Parent
description: Calls local action
runs:
  using: composite
  steps:
    - uses: ./actions/greet
      with:
        who: world
`,
    { serializer: (yaml) => yaml },
  );
});

Deno.test("rendered composite metadata exposes an external Action contract", async () => {
  const draft = defineCompositeAction("actions/greet/action.yml", {
    name: "Greet",
    description: "Greeting",
    author: "Example",
    branding: { icon: "terminal", color: "blue" },
    inputs: { who: { description: "Recipient", required: true } },
    outputs: { greeting: { description: "Greeting" } },
  });
  const action = draft.steps(({ step }) =>
    step.run({
      id: "greet",
      name: "Greet",
      shell: "bash",
      run: 'echo "greeting=hello" >> "$GITHUB_OUTPUT"\n',
      outputs: ["greeting"],
      env: { WHO: draft.inputs.who },
      if: ({ inputs }) => inputs.who.ne(""),
    }).outputs(({ steps }) => ({ greeting: steps.greet.outputs.greeting }))
  );
  const [file] = await generateFiles(
    defineProject({ actions: [action] }),
    "./actions.ts",
    "unused",
  );
  const yaml = String(file.content);
  const contract = generateV1(
    yaml,
    "acme/actions/actions/greet@" + "a".repeat(40),
    "https://example.com/action.yml",
  );
  assertStringIncludes(contract, "greeting");
  assert(!contract.includes('"runs"'));
});

Deno.test("composite metadata collection includes referenced actions and deduplicates identities", async () => {
  const action = defineCompositeAction("actions/greet/action.yml", {
    name: "Greet",
    description: "Greeting",
  })
    .steps(({ step }) =>
      step.run({ name: "Greet", shell: "bash", run: "true" })
    );
  const workflow = defineWorkflow(".github/workflows/greet.yml", {
    on: { push: {} },
  })
    .job("greet", ({ job }) => job.runsOn("ubuntu-latest").uses(action));
  assertEquals(
    (await generateFiles(
      defineProject({ workflows: [workflow] }),
      "./actions.ts",
      "unused",
    )).map((file) => file.path),
    [".github/workflows/greet.yml", "actions/greet/action.yml"],
  );
  assertEquals(
    (await generateFiles(
      defineProject({ actions: [action] }),
      "./actions.ts",
      "unused",
    )).length,
    1,
  );
  assertEquals(
    lowerProject(defineProject({ actions: [action, action] }), "actions.ts")
      .actions.length,
    1,
  );
});

Deno.test("composite definitions reject missing outputs, invalid paths, and empty projects", async () => {
  const draft = defineCompositeAction("actions/greet/action.yml", {
    name: "Greet",
    description: "Greeting",
    outputs: { greeting: { description: "Greeting" } },
  });
  assertThrows(
    () =>
      draft.steps(({ step }) =>
        step.run({ name: "Missing mapping", shell: "bash", run: "true" })
      ),
    TypeError,
    "output mappings",
  );
  assertThrows(
    () =>
      defineCompositeAction("../escape", { name: "Bad", description: "Bad" }),
    TypeError,
  );
  await assertRejects(
    () => generateFiles(defineProject({}), "empty.ts", "unused"),
    Error,
    "at least one",
  );
});

Deno.test("generated Action bootstrap stays synchronized with workflow preparation", async () => {
  assertEquals(
    TASK_PREPARE_SCRIPT,
    await Deno.readTextFile(resolve("actions/task-prepare/prepare.sh")),
  );
});

Deno.test("Composite collection shares nested identities and orders metadata paths", async () => {
  const leaf = defineCompositeAction("actions/shared/action.yaml", {
    name: "Shared",
    description: "Shared",
  }).steps(({ step }) =>
    step.run({ name: "Leaf", shell: "bash", run: "true" })
  );
  const parent = (path: string) =>
    defineCompositeAction(path, { name: "Parent", description: "Parent" })
      .steps(({ step }) => step.uses(leaf).uses(leaf));
  const a = parent("actions/a/action.yml");
  const z = parent("actions/z/action.yml");
  const workflow = defineWorkflow("ci.yml", { on: { push: {} } }).job(
    "ci",
    ({ job }) => job.runsOn("ubuntu-latest").uses(z).uses(a),
  );
  const paths = (project: ReturnType<typeof defineProject>) =>
    generateFiles(project, "actions.ts", "unused").then((files) =>
      files.map((f) => f.path)
    );
  const expected = [
    "ci.yml",
    "actions/a/action.yml",
    "actions/shared/action.yaml",
    "actions/z/action.yml",
  ];
  assertEquals(
    await paths(
      defineProject({ workflows: [workflow], actions: [z, leaf, a, leaf] }),
    ),
    expected,
  );
  assertEquals(
    await paths(defineProject({ workflows: [workflow], actions: [a, z] })),
    expected,
  );
  assertEquals(
    await paths(defineProject({ actions: [z, a] })),
    expected.slice(1),
  );
  const override = defineWorkflow("remote.yml", { on: { push: {} } }).job(
    "ci",
    ({ job }) =>
      job.runsOn("ubuntu-latest").uses(leaf, { uses: "example/action@v1" }),
  );
  assertEquals(await paths(defineProject({ workflows: [override] })), [
    "remote.yml",
  ]);
});

Deno.test("root and nested composite paths render relative to the project directory", async () => {
  const root = defineCompositeAction("action.yml", {
    name: "Root",
    description: "Root",
  })
    .steps(({ step }) => step.run({ name: "Run", shell: "bash", run: "true" }));
  const nested = defineCompositeAction("actions/./greet/action.yaml", {
    name: "Nested",
    description: "Nested",
  })
    .steps(({ step }) => step.run({ name: "Run", shell: "bash", run: "true" }));
  const parent = defineCompositeAction("actions/parent/action.yml", {
    name: "Parent",
    description: "Parent",
  })
    .steps(({ step }) => step.uses(root).uses(nested));
  const workflow = defineWorkflow("ci.yml", { on: { push: {} } }).job(
    "ci",
    ({ job }) =>
      job.runsOn("ubuntu-latest").uses(root).uses(nested).uses(parent),
  );
  const files = await generateFiles(
    defineProject({ workingDirectory: ".github", workflows: [workflow] }),
    "actions.ts",
    "unused",
  );
  const atRoot = await generateFiles(
    defineProject({ workflows: [workflow] }),
    "actions.ts",
    "unused",
  );
  assertInlineSnapshot(
    String(files[0].content),
    `# Generated by Tsugiori from actions.ts
name: ci.yml
on:
  push: {}
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github

      - uses: ./.github/actions/greet

      - uses: ./.github/actions/parent
`,
    { serializer: (yaml) => yaml },
  );
  assertInlineSnapshot(
    String(atRoot[0].content),
    `# Generated by Tsugiori from actions.ts
name: ci.yml
on:
  push: {}
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: ./

      - uses: ./actions/greet

      - uses: ./actions/parent
`,
    { serializer: (yaml) => yaml },
  );
  assertInlineSnapshot(
    String(files[3].content),
    `# Generated by Tsugiori from actions.ts
name: Parent
description: Parent
runs:
  using: composite
  steps:
    - uses: ./.github
    - uses: ./.github/actions/greet
`,
    {
      serializer: (yaml) => yaml,
    },
  );
  assertInlineSnapshot(
    String(atRoot[3].content),
    `# Generated by Tsugiori from actions.ts
name: Parent
description: Parent
runs:
  using: composite
  steps:
    - uses: ./
    - uses: ./actions/greet
`,
    {
      serializer: (yaml) => yaml,
    },
  );
});

Deno.test("composite metadata paths normalize directories and reject placement conflicts", async () => {
  const make = (path: string) =>
    defineCompositeAction(path, { name: "Root", description: "Root" }).steps((
      { step },
    ) => step.run({ name: "Run", shell: "bash", run: "true" }));
  for (
    const path of [
      "action.yml",
      "action.yaml",
      "./action.yml",
      "actions/./greet/action.yaml",
    ]
  ) {
    const action = make(path);
    const workflow = defineWorkflow("ci.yml", { on: { push: {} } }).job(
      "ci",
      ({ job }) => job.runsOn("ubuntu-latest").uses(action),
    );
    const project = defineProject({
      workingDirectory: ".github",
      workflows: [workflow],
    });
    const files = await generateFiles(project, "actions.ts", "unused");
    assertEquals(files[1].path, path.replace(/^\.\//, "").replace("/./", "/"));
    if (!path.startsWith("actions/")) {
      assertEquals(action.uses, "./");
    }
  }
  for (
    const invalid of [
      "actions/greet",
      "actions/greet/",
      "other.yml",
      "../action.yml",
      "/action.yml",
      "a//action.yml",
    ]
  ) {
    assertThrows(
      () => make(invalid),
      TypeError,
      "action.yml or action.yaml file",
    );
  }
  for (const path of ["action.yml", "action.yaml"]) {
    assertThrows(
      () =>
        lowerProject(
          defineProject({ actions: [make("action.yml"), make(path)] }),
          "actions.ts",
        ),
      Error,
      "directory . is duplicated",
    );
  }
});

Deno.test("shared Composite traversal retains cycle and deep-path checks", () => {
  const leaf = defineCompositeAction("leaf/action.yml", {
    name: "Leaf",
    description: "Leaf",
  }).steps(({ step }) => step.run({ name: "Run", shell: "bash", run: "true" }));
  let nested = leaf;
  for (let depth = 1; depth < 10; depth++) {
    const child = nested;
    nested = defineCompositeAction(`level${depth}/action.yml`, {
      name: "Leaf",
      description: "Leaf",
    }).steps(({ step }) => step.uses(child));
  }
  const workflow = (action: typeof leaf) =>
    defineWorkflow("ci.yml", { on: { push: {} } }).job(
      "ci",
      ({ job }) => job.runsOn("ubuntu-latest").uses(leaf).uses(action),
    );
  assertEquals(
    lowerProject(
      defineProject({ workflows: [workflow(nested)], actions: [leaf] }),
      "actions.ts",
    ).actions.length,
    10,
  );
  const tooDeep = defineCompositeAction("deep/action.yml", {
    name: "Leaf",
    description: "Leaf",
  }).steps(({ step }) => step.uses(nested));
  assertThrows(
    () =>
      lowerProject(
        defineProject({ workflows: [workflow(tooDeep)], actions: [leaf] }),
        "actions.ts",
      ),
    Error,
    "exceeds ten levels",
  );
  const materialized = defineProject({ actions: [leaf] }).actions![0];
  const steps: import("../src/github_actions/mod.ts").AuthoringStep[] = [];
  const cyclic = {
    ...materialized,
    runs: { using: "composite" as const, steps },
  };
  steps.push({
    type: "uses",
    name: "Cycle",
    uses: "./leaf",
    calleeAction: cyclic,
  });
  assertThrows(
    () =>
      lowerProject(
        { ...defineProject({ actions: [leaf] }), actions: [cyclic] },
        "actions.ts",
      ),
    Error,
    "cycle",
  );
});

Deno.test("scenario accepts an automatically collected Composite with native fixtures", async () => {
  const action = defineCompositeAction("actions/fixture/action.yml", {
    name: "Fixture",
    description: "Fixture",
    outputs: { value: { description: "Value" } },
  }).steps(({ step }) =>
    step.run({
      id: "produce",
      name: "Produce",
      shell: "bash",
      run: "true",
      outputs: ["value"],
    }).outputs(({ steps }) => ({ value: steps.produce.outputs.value }))
  );
  const workflow = defineWorkflow("ci.yml", { on: { push: {} } }).job(
    "ci",
    ({ job }) =>
      job.runsOn("ubuntu-latest").uses(action, { id: "call" }).run({
        id: "consume",
        name: "Consume",
        run: "true",
        env: ({ steps }) => ({ VALUE: steps.call.outputs.value }),
      }),
  );
  const result = await scenario(workflow, (test) => {
    test.github({ event_name: "push", ref: "refs/heads/main", event: {} });
    test.job("ci", (job) => {
      job.step("call").fixture({ outputs: { value: "" } }).expectRun();
      job.step("consume").fixture({}).expectRun();
    });
  });
  assertEquals(result.result, "success");
  assertEquals(result.jobs.ci.instances[0].steps.consume.env, { VALUE: "" });
});

Deno.test("workflow and composite YAML preserve scalar values with natural quoting", async () => {
  const values = {
    description:
      "The version of mise to use. If not specified, will use the latest release.",
    expr: "${{ github.ref }}",
    cache: "cache-${{ runner.os }}",
    url: "https://example.com/foo#bar",
    booleanString: "false",
    numberString: "123",
    empty: "",
    spaces: " a ",
    colon: "a: b",
    comment: "a # comment",
    long: "word ".repeat(50).trimEnd(),
  };
  const commands = [
    "echo hello",
    "echo first\necho second",
    "echo trailing\n",
    "echo keep\n\n",
    " echo leading space",
    "printf x\t| cat",
    "echo\rvalue",
  ];
  const action = defineCompositeAction("actions/scalars/action.yml", {
    name: "Scalars",
    description: values.description,
  }).steps(({ step }) =>
    commands.slice(1).reduce(
      (steps, run) => steps.run({ name: "Run", run, shell: "bash" }),
      step.run({ name: "First", run: commands[0], shell: "bash", env: values }),
    )
  );
  const workflow = defineWorkflow(".github/workflows/scalars.yml", {
    on: { push: {} },
  }).job("test", ({ job }) =>
    commands.slice(1).reduce(
      (steps, run) => steps.run({ name: "Run", run }),
      job.runsOn("ubuntu-latest").run({
        name: "First",
        run: commands[0],
        env: values,
      }),
    ));
  const files = await generateFiles(
    defineProject({ workflows: [workflow], actions: [action] }),
    "./scalars.ts",
    "unused",
  );
  for (const file of files) {
    assert(typeof file.content === "string");
    const yaml = file.content;
    assert(yaml.startsWith("# Generated by Tsugiori from scalars.ts\n"));
    const decoded = parse(yaml) as {
      jobs?: { test: { steps: { run: string; env?: typeof values }[] } };
      runs?: { steps: { run: string; env?: typeof values }[] };
    };
    const steps = decoded.jobs?.test.steps ?? decoded.runs!.steps;
    assertEquals(steps.map((step) => step.run), commands);
    assertEquals(steps[0].env, values);
    for (
      const key of ["description", "expr", "cache", "url", "long"] as const
    ) {
      assertStringIncludes(yaml, `${key}: ${values[key]}\n`);
    }
    for (
      const key of [
        "booleanString",
        "numberString",
        "empty",
        "spaces",
        "colon",
        "comment",
      ] as const
    ) {
      assert(new RegExp(`${key}: ["']`).test(yaml));
    }
    assertEquals(/(?:^|\s)[&*][\w-]+/.test(yaml), false);
    if (decoded.runs) assertEquals(/\n\n +-(?: |$)/m.test(yaml), false);
  }
});
