import { assertEquals, assertRejects } from "@std/assert";
import { resolve } from "node:path";
import { checkGeneratedFiles } from "../packages/compiler/src/check.ts";
import type { GeneratedFile } from "../packages/compiler/src/generator.ts";
import { writeGeneratedFiles } from "../packages/compiler/src/write.ts";

const owner = "./.github/tsugiori.ts";
const firstPath = ".github/workflows/first.yml";
const secondPath = ".github/workflows/second.yml";
const extraPath = ".github/workflows/extra.yml";
const files: readonly GeneratedFile[] = [
  {
    path: firstPath,
    content: "# Generated by Tsugiori from .github/tsugiori.ts\nname: first\n",
  },
  {
    path: secondPath,
    content: "# Generated by Tsugiori from .github/tsugiori.ts\nname: second\n",
  },
];

Deno.test("check mode scopes comparisons and detects missing, changed, and extra owned files", async () => {
  const root = await Deno.makeTempDir({ prefix: "tsugiori-check-" });
  try {
    await writeGeneratedFiles(root, files);
    const checkAll = () => checkGeneratedFiles(root, owner, files);
    const checkOne = (path: string) =>
      checkGeneratedFiles(root, owner, files, path);
    assertEquals(await checkAll(), []);
    assertEquals(await checkOne(firstPath), []);

    await Deno.remove(resolve(root, secondPath));
    assertEquals(await checkOne(firstPath), []);
    assertEquals(await checkOne(secondPath), [
      { path: secondPath, reason: "missing" },
    ]);
    assertEquals(await checkAll(), [
      { path: secondPath, reason: "missing" },
    ]);
    await assertRejects(
      () => Deno.stat(resolve(root, secondPath)),
      Deno.errors.NotFound,
    );

    await Deno.writeTextFile(resolve(root, secondPath), files[1].content);
    const changed = `${files[0].content}# local edit\n`;
    await Deno.writeTextFile(resolve(root, firstPath), changed);
    assertEquals(await checkOne(firstPath), [
      { path: firstPath, reason: "changed" },
    ]);
    assertEquals(await checkAll(), [
      { path: firstPath, reason: "changed" },
    ]);
    assertEquals(await Deno.readTextFile(resolve(root, firstPath)), changed);

    await Deno.writeTextFile(resolve(root, firstPath), files[0].content);
    const extra =
      "# Generated by Tsugiori from .github/tsugiori.ts\nname: extra\n";
    await Deno.writeTextFile(resolve(root, extraPath), extra);
    await Deno.writeTextFile(
      resolve(root, ".github/workflows/handwritten.yml"),
      "name: handwritten\n",
    );
    await Deno.writeTextFile(
      resolve(root, ".github/workflows/other.yml"),
      "# Generated by Tsugiori from .github/other.ts\nname: other\n",
    );
    assertEquals(await checkOne(firstPath), []);
    assertEquals(await checkOne(extraPath), [
      { path: extraPath, reason: "extra" },
    ]);
    assertEquals(await checkAll(), [
      { path: extraPath, reason: "extra" },
    ]);
    assertEquals(await Deno.readTextFile(resolve(root, extraPath)), extra);

    await assertRejects(
      () => checkOne(".github/workflows/handwritten.yml"),
      Error,
      "not generated by",
    );
  } finally {
    await Deno.remove(root, { recursive: true });
  }
});
