import { assertInlineSnapshot } from "@std/testing/unstable-snapshot";
import { assert, assertEquals, assertRejects, assertThrows } from "@std/assert";
import { parse } from "../src/deps.ts";
import { project, workflow } from "../src/github_actions/mod.ts";
import { generateFiles } from "../src/compiler/generator.ts";

Deno.test("prepare Action installs the repository's verified toolchain and forwards inputs/output", async () => {
  const action = parse(
    await Deno.readTextFile("actions/task-prepare/action.yml"),
  ) as {
    inputs: Record<string, unknown>;
    outputs: Record<string, { value: string }>;
    runs: { using: string; steps: { env: Record<string, string> }[] };
  };
  const toolchain = await Deno.readTextFile("mise.toml");
  assertEquals(action.runs.using, "composite");
  const env = action.runs.steps[0].env;
  assertEquals(
    env.TSUGIORI_INSTALL_DENO_VERSION,
    toolchain.match(/^deno = "([^"]+)"$/m)?.[1],
  );
  for (const input of Object.keys(action.inputs)) {
    assert(Object.values(env).includes(`\${{ inputs.${input} }}`));
  }
  assertEquals(
    action.outputs["runtime-path"].value,
    "${{ steps.prepare.outputs.runtime-path }}",
  );
});

Deno.test("task generation renders the explicit local preparation Action and project directory", async () => {
  const ci = workflow("ci.yml", { on: { push: {} } }).job(
    "test",
    ({ job }) =>
      job.runsOn("ubuntu-latest").task({
        name: "Task",
        inputs: {},
        outputs: {},
        run: () => {},
      }),
  );
  const [file] = await generateFiles(
    project({
      workingDirectory: "project",
      localTaskPrepareAction: "./actions/task-prepare",
      workflows: [ci],
    }),
    "./workflows.ts",
    "source",
  );
  assertInlineSnapshot(
    String(file.content),
    `# Generated by Tsugiori from workflows.ts
name: ci.yml
on:
  push: {}
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Cache task artifact
        id: tsugiori-task-cache
        continue-on-error: true
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9
        with:
          path: \${{ runner.temp }}/tsugiori-artifacts/source-\${{ runner.os }}-\${{ runner.arch }}
          key: tsugiori-task-source-\${{ runner.os }}-\${{ runner.arch }}

      - name: Prepare task artifact
        id: tsugiori-task-prepare
        uses: ./actions/task-prepare
        with:
          project-directory: project
          entrypoint: ./workflows.ts
          source-key: source
          cache-directory: \${{ runner.temp }}/tsugiori-artifacts/source-\${{ runner.os }}-\${{ runner.arch }}

      - name: Task
        run: "\\"\${{ steps.tsugiori-task-prepare.outputs.runtime-path }}\\" 'ci.yml/test/task-1'"
`,
    { serializer: (yaml) => yaml },
  );
});

Deno.test("native-only generation needs no task preparation identity", async () => {
  const native = workflow("ci.yml", { on: { push: {} } }).job(
    "test",
    ({ job }) => job.runsOn("ubuntu-latest").run({ name: "Test", run: "true" }),
  );
  const files = await generateFiles(
    project({ workflows: [native] }),
    "./workflows.ts",
    "source",
  );
  assertEquals(files.length, 1);
  const [file] = files;
  assertInlineSnapshot(
    String(file.content),
    `# Generated by Tsugiori from workflows.ts
name: ci.yml
on:
  push: {}
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: "true"
`,
    { serializer: (yaml) => yaml },
  );
});

Deno.test("task generation requires release identity and validates local preparation paths", async () => {
  const ci = workflow("ci.yml", { on: { push: {} } }).job(
    "test",
    ({ job }) =>
      job.runsOn("ubuntu-latest").task({
        name: "Task",
        inputs: {},
        outputs: {},
        run: () => {},
      }),
  );
  await assertRejects(
    () =>
      generateFiles(
        project({ workflows: [ci] }),
        "./workflows.ts",
        "source",
      ),
    Error,
    "localTaskPrepareAction",
  );
  for (
    const path of [
      "actions/prepare",
      "../prepare",
      "./../prepare",
      "./actions/../prepare",
      "./a@main",
      "./a\nrun: bad",
    ]
  ) {
    assertThrows(
      () => project({ localTaskPrepareAction: path, workflows: [ci] }),
      TypeError,
    );
  }
});
