import { assert, assertEquals, assertStringIncludes } from "@std/assert";
import { resolve } from "node:path";
import { pathToFileURL } from "node:url";

Deno.test({
  name:
    "config entrypoint generates, prepares, caches, and dispatches a task artifact",
  sanitizeOps: false,
  sanitizeResources: false,
  fn: async () => {
    const repositoryRoot = Deno.cwd();
    const fixture = await Deno.makeTempDir({ prefix: "tsugiori-e2e-" });
    try {
      await copyDirectory(
        resolve(repositoryRoot, "packages"),
        resolve(fixture, "packages"),
      );
      await Deno.copyFile(
        resolve(repositoryRoot, "deno.json"),
        resolve(fixture, "deno.json"),
      );
      await Deno.copyFile(
        resolve(repositoryRoot, "deno.lock"),
        resolve(fixture, "deno.lock"),
      );
      await Deno.mkdir(resolve(fixture, ".github"));
      await Deno.writeTextFile(
        resolve(fixture, ".github/deno.json"),
        JSON.stringify({
          imports: {
            "@atty303/tsugiori": "workspace:*",
            "consumer-only": "./consumer-only.ts",
          },
          tasks: {
            generate: "deno run --frozen=true -A ./tsugiori.ts generate",
            "generate:check":
              "deno run --frozen=true -A ./tsugiori.ts generate --check",
          },
        }),
      );
      await Deno.writeTextFile(
        resolve(fixture, ".github/consumer-only.ts"),
        "export const consumerMarker = true;\n",
      );
      const configSource = `import { consumerMarker } from "consumer-only";
void consumerMarker;
import { defineTsugiori, pipeline } from "@atty303/tsugiori/github-actions";
import { runTsugiori } from "@atty303/tsugiori/run";

const base = pipeline("ci", {
  output: ".github/workflows/ci.yml",
  events: ["push"],
});
try {
  Deno.statSync("fail-config");
  throw new Error("config-load-private");
} catch (error) {
  if (!(error instanceof Deno.errors.NotFound)) throw error;
}
const ci = base.job("test", ({ job }) =>
  job
    .runsOn("ubuntu-latest")
    .run({ name: "Setup", run: "echo setup" })
    .task({
      name: "Test",
      task: async (ctx) => {
        ctx.logger.info("task-log-private");
        if (Deno.env.get("TSUGIORI_TASK_FAILURE") === "1") {
          Object.defineProperty(WeakMap.prototype, "get", {
            value: () => "task-error-type-private",
          });
          const error = new Error("task-failure-private") as Error & {
            errorType: string;
          };
          error.errorType = "task-error-type-private";
          throw error;
        }
        await Deno.writeTextFile("task-result.txt", ctx.cwd);
      },
    })
);

const config = defineTsugiori({ pipelines: [ci] });
export default config;
if (import.meta.main) Deno.exitCode = await runTsugiori({ config, configUrl: import.meta.url, root: new URL("../", import.meta.url) });
`;
      await Deno.writeTextFile(
        resolve(fixture, ".github/tsugiori.ts"),
        configSource,
      );

      const environment: Record<string, string> = {
        ...Deno.env.toObject(),
      };
      delete environment.RUNNER_DEBUG;
      assertEquals(environment.RUNNER_DEBUG, undefined);

      const generated = await run(
        Deno.execPath(),
        ["task", "generate"],
        resolve(fixture, ".github"),
        environment,
      );
      assertEquals(generated.code, 0, generated.stderr);
      const workflow = await Deno.readTextFile(
        resolve(fixture, ".github/workflows/ci.yml"),
      );
      assertStringIncludes(
        workflow,
        "# Generated by Tsugiori from .github/tsugiori.ts\n",
      );
      const checked = await runTsugiori(
        [
          "generate",
          "--check",
          "--output",
          ".github/workflows/ci.yml",
        ],
        fixture,
        environment,
      );
      assertEquals(checked.code, 0, checked.stderr);
      const checkedAll = await run(
        Deno.execPath(),
        ["task", "generate:check"],
        resolve(fixture, ".github"),
        environment,
      );
      assertEquals(checkedAll.code, 0, checkedAll.stderr);
      assertEquals(
        await Deno.readTextFile(resolve(fixture, ".github/workflows/ci.yml")),
        workflow,
      );
      assertStringIncludes(workflow, "name: Resolve task artifact");
      assertStringIncludes(workflow, "name: Restore task artifact cache");
      assertStringIncludes(workflow, "name: Prepare task artifact");
      assertStringIncludes(workflow, "name: Save task artifact cache");
      assertStringIncludes(workflow, "working-directory: .github");
      assertStringIncludes(
        workflow,
        "deno run --frozen=true -A ''./tsugiori.ts'' github-actions task cache-key",
      );
      assertStringIncludes(workflow, "actions/cache/restore@");
      assertStringIncludes(workflow, "actions/cache/save@");
      assertStringIncludes(
        workflow,
        "run: ./.tsugiori/task-runtime ci/test/task-1",
      );
      const expectedLayout = workflow.match(/ci\/test=sha256:[0-9a-f]+/)?.[0];
      assert(expectedLayout !== undefined);
      const githubOutput = resolve(fixture, "github-output");

      await Deno.writeTextFile(
        resolve(fixture, ".github/tsugiori.ts"),
        configSource.replace('name: "Test"', 'name: "Changed"'),
      );
      const staleWorkflow = await runTsugiori(
        [
          "generate",
          "--check",
          "--output",
          ".github/workflows/ci.yml",
        ],
        fixture,
        environment,
      );
      assertEquals(staleWorkflow.code, 1);
      assertStringIncludes(
        staleWorkflow.stderr,
        "changed: .github/workflows/ci.yml",
      );
      assertEquals(
        await Deno.readTextFile(resolve(fixture, ".github/workflows/ci.yml")),
        workflow,
      );
      await Deno.writeTextFile(githubOutput, "");
      const stale = await runTsugiori(
        [
          "github-actions",
          "task",
          "cache-key",
          "--expect-layout",
          expectedLayout,
        ],
        fixture,
        {
          ...environment,
          GITHUB_OUTPUT: githubOutput,
          RUNNER_DEBUG: "1",
        },
      );
      assertEquals(stale.code, 1);
      assertStringIncludes(stale.stderr, "task layout is stale");
      const staleRecord = diagnosticRecord(stale.stderr);
      assert(staleRecord !== undefined);
      assertEquals(
        staleRecord.operations.at(-1)?.errorType,
        "registry_layout_mismatch",
      );
      await Deno.writeTextFile(
        resolve(fixture, ".github/tsugiori.ts"),
        configSource,
      );

      await Deno.writeTextFile(githubOutput, "");
      const resolvedArtifact = await runTsugiori(
        [
          "github-actions",
          "task",
          "cache-key",
          "--expect-layout",
          expectedLayout,
        ],
        fixture,
        { ...environment, GITHUB_OUTPUT: githubOutput },
      );
      assertEquals(resolvedArtifact.code, 0, resolvedArtifact.stderr);
      const firstOutputs = parseGitHubOutputs(
        await Deno.readTextFile(githubOutput),
      );
      const artifactKey = firstOutputs["artifact-key"];
      assert(artifactKey !== undefined);
      assertEquals(
        firstOutputs["cache-path"],
        `.tsugiori/cache/artifacts/${artifactKey}`,
      );

      await Deno.writeTextFile(githubOutput, "");
      const firstPrepare = await runTsugiori(
        [
          "github-actions",
          "task",
          "prepare",
          "--expect-layout",
          expectedLayout,
          "--expected-key",
          artifactKey,
        ],
        fixture,
        { ...environment, GITHUB_OUTPUT: githubOutput },
      );
      assertEquals(firstPrepare.code, 0, firstPrepare.stderr);
      assertStringIncludes(firstPrepare.stdout, "cache miss");
      assertEquals(
        parseGitHubOutputs(await Deno.readTextFile(githubOutput))[
          "cache-write-required"
        ],
        "true",
      );

      await Deno.remove(resolve(fixture, ".tsugiori/task-runtime"));
      await Deno.remove(resolve(fixture, ".tsugiori/task-runtime.json"));
      await Deno.writeTextFile(githubOutput, "");
      const secondPrepare = await runTsugiori(
        [
          "github-actions",
          "task",
          "prepare",
          "--expect-layout",
          expectedLayout,
          "--expected-key",
          artifactKey,
        ],
        fixture,
        { ...environment, GITHUB_OUTPUT: githubOutput },
      );
      assertEquals(secondPrepare.code, 0, secondPrepare.stderr);
      assertStringIncludes(secondPrepare.stdout, "cache hit");
      assertEquals(
        parseGitHubOutputs(await Deno.readTextFile(githubOutput))[
          "cache-write-required"
        ],
        "false",
      );

      await Deno.writeTextFile(
        resolve(fixture, ".github/deno.json"),
        JSON.stringify({
          imports: {
            "@atty303/tsugiori": "workspace:*",
            "consumer-only": "./consumer-only.ts",
          },
          compilerOptions: { strict: true },
        }),
      );
      await Deno.writeTextFile(githubOutput, "");
      const configurationOnlyChange = await runTsugiori(
        [
          "github-actions",
          "task",
          "prepare",
          "--expect-layout",
          expectedLayout,
          "--expected-key",
          artifactKey,
        ],
        fixture,
        {
          ...environment,
          GITHUB_OUTPUT: githubOutput,
        },
      );
      assertEquals(
        configurationOnlyChange.code,
        0,
        configurationOnlyChange.stderr,
      );
      assertStringIncludes(configurationOnlyChange.stdout, "cache hit");
      assertEquals(
        parseGitHubOutputs(await Deno.readTextFile(githubOutput))[
          "cache-write-required"
        ],
        "false",
      );

      await Deno.writeTextFile(
        resolve(fixture, ".github/tsugiori.ts"),
        configSource.replace("echo setup", "echo changed-setup"),
      );
      await Deno.writeTextFile(githubOutput, "");
      const keyChangedDuringPreparation = await runTsugiori(
        [
          "github-actions",
          "task",
          "prepare",
          "--expect-layout",
          expectedLayout,
          "--expected-key",
          artifactKey,
        ],
        fixture,
        {
          ...environment,
          GITHUB_OUTPUT: githubOutput,
          RUNNER_DEBUG: "1",
        },
      );
      assertEquals(keyChangedDuringPreparation.code, 1);
      assertStringIncludes(
        keyChangedDuringPreparation.stderr,
        "inputs changed after the cache key was resolved",
      );
      assertEquals(
        diagnosticRecord(keyChangedDuringPreparation.stderr)?.operations.at(-1)
          ?.errorType,
        "artifact_key_mismatch",
      );

      await Deno.writeTextFile(githubOutput, "");
      const changedArtifact = await runTsugiori(
        [
          "github-actions",
          "task",
          "cache-key",
          "--expect-layout",
          expectedLayout,
        ],
        fixture,
        { ...environment, GITHUB_OUTPUT: githubOutput },
      );
      assertEquals(changedArtifact.code, 0, changedArtifact.stderr);
      const changedArtifactKey = parseGitHubOutputs(
        await Deno.readTextFile(githubOutput),
      )["artifact-key"];
      assert(changedArtifactKey !== undefined);
      assert(changedArtifactKey !== artifactKey);

      await Deno.writeTextFile(githubOutput, "");
      const configurationChanged = await runTsugiori(
        [
          "github-actions",
          "task",
          "prepare",
          "--expect-layout",
          expectedLayout,
          "--expected-key",
          changedArtifactKey,
        ],
        fixture,
        { ...environment, GITHUB_OUTPUT: githubOutput },
      );
      assertEquals(configurationChanged.code, 0, configurationChanged.stderr);
      assertStringIncludes(configurationChanged.stdout, "cache miss");
      assertEquals(
        parseGitHubOutputs(await Deno.readTextFile(githubOutput))[
          "cache-write-required"
        ],
        "true",
      );

      const materializedManifest = JSON.parse(
        await Deno.readTextFile(
          resolve(fixture, ".tsugiori/task-runtime.json"),
        ),
      ) as {
        artifactKey: string;
        schemaVersion: number;
        tsugioriBuildId?: unknown;
        tsugioriVersion: string;
      };
      assertEquals(materializedManifest.schemaVersion, 2);
      assertEquals(
        materializedManifest.tsugioriVersion,
        "0.1.0",
      );
      assertEquals("tsugioriBuildId" in materializedManifest, false);
      await Deno.writeTextFile(
        resolve(
          fixture,
          `.tsugiori/cache/artifacts/${materializedManifest.artifactKey}/task-runtime`,
        ),
        "corrupt",
      );
      await Deno.remove(resolve(fixture, ".tsugiori/task-runtime"));
      await Deno.remove(resolve(fixture, ".tsugiori/task-runtime.json"));
      await Deno.writeTextFile(githubOutput, "");
      const recovered = await runTsugiori(
        [
          "github-actions",
          "task",
          "prepare",
          "--expect-layout",
          expectedLayout,
          "--expected-key",
          changedArtifactKey,
        ],
        fixture,
        { ...environment, GITHUB_OUTPUT: githubOutput },
      );
      assertEquals(recovered.code, 0, recovered.stderr);
      assertStringIncludes(recovered.stdout, "cache miss");
      assertEquals(
        parseGitHubOutputs(await Deno.readTextFile(githubOutput))[
          "cache-write-required"
        ],
        "true",
      );

      await Deno.chmod(
        resolve(
          fixture,
          `.tsugiori/cache/artifacts/${changedArtifactKey}/task-runtime`,
        ),
        0o000,
      );
      await Deno.remove(resolve(fixture, ".tsugiori/task-runtime"));
      await Deno.remove(resolve(fixture, ".tsugiori/task-runtime.json"));
      await Deno.writeTextFile(githubOutput, "");
      const unreadableEntry = await runTsugiori(
        [
          "github-actions",
          "task",
          "prepare",
          "--expect-layout",
          expectedLayout,
          "--expected-key",
          changedArtifactKey,
        ],
        fixture,
        {
          ...environment,
          GITHUB_OUTPUT: githubOutput,
          RUNNER_DEBUG: "1",
        },
      );
      assertEquals(unreadableEntry.code, 0, unreadableEntry.stderr);
      assertStringIncludes(unreadableEntry.stdout, "cache miss");
      assertEquals(
        parseGitHubOutputs(await Deno.readTextFile(githubOutput))[
          "cache-write-required"
        ],
        "true",
      );
      assertEquals(
        diagnosticRecord(unreadableEntry.stderr)?.operations.filter(
          (operation) => operation.name === "cache.restore",
        ),
        [{
          name: "cache.restore",
          status: "error",
          errorType: "cache_restore_failed",
          attributes: { artifactKey: changedArtifactKey },
        }],
      );

      const runtime = resolve(fixture, ".tsugiori/task-runtime");
      const executed = await run(
        runtime,
        ["ci/test/task-1"],
        fixture,
        environment,
      );
      assertEquals(executed.code, 0, executed.stderr);
      assertStringIncludes(executed.stdout, "task-log-private");
      assertEquals(diagnosticRecord(executed.stderr), undefined);
      assertEquals(
        await Deno.readTextFile(resolve(fixture, "task-result.txt")),
        await Deno.realPath(fixture),
      );

      const debugged = await run(
        runtime,
        ["ci/test/task-1"],
        fixture,
        { ...environment, RUNNER_DEBUG: "1" },
      );
      assertEquals(debugged.code, 0, debugged.stderr);
      const debugRecord = diagnosticRecord(debugged.stderr);
      assert(debugRecord !== undefined);
      assertEquals(
        debugRecord.operations[0],
        {
          name: "task.dispatch",
          status: "success",
          attributes: { entrypoint: "ci/test/task-1" },
        },
      );
      assertEquals(debugRecord.status, "success");
      assertEquals(debugRecord.completeness, "complete");
      assertEquals(debugged.stderr.includes("task-log-private"), false);

      const taskFailure = await run(
        runtime,
        ["ci/test/task-1"],
        fixture,
        {
          ...environment,
          RUNNER_DEBUG: "1",
          TSUGIORI_TASK_FAILURE: "1",
        },
      );
      assertEquals(taskFailure.code, 1);
      assertStringIncludes(taskFailure.stderr, "task-failure-private");
      const taskFailureRecord = diagnosticRecord(taskFailure.stderr);
      assert(taskFailureRecord !== undefined);
      assertEquals(taskFailureRecord.operations[0].errorType, "task_failed");
      assertEquals(
        taskFailure.stderr.includes("task-error-type-private"),
        false,
      );

      await Deno.writeTextFile(resolve(fixture, "fail-config"), "fail\n");
      const configFailure = await run(
        runtime,
        ["ci/test/task-1"],
        fixture,
        { ...environment, RUNNER_DEBUG: "1" },
      );
      assertEquals(configFailure.code, 1);
      assertStringIncludes(configFailure.stderr, "config-load-private");
      assertEquals(diagnosticRecord(configFailure.stderr), undefined);
      await Deno.writeTextFile(
        resolve(fixture, ".github/fail-config"),
        "fail\n",
      );
      const directConfigFailure = await run(
        Deno.execPath(),
        ["run", "--frozen=true", "-A", "./tsugiori.ts", "generate", "--check"],
        resolve(fixture, ".github"),
        { ...environment, RUNNER_DEBUG: "1" },
      );
      assertEquals(directConfigFailure.code, 1);
      assertStringIncludes(directConfigFailure.stderr, "config-load-private");
      assertEquals(diagnosticRecord(directConfigFailure.stderr), undefined);
      await Deno.remove(resolve(fixture, "fail-config"));
      await Deno.remove(resolve(fixture, ".github/fail-config"));

      const unknown = await run(
        runtime,
        ["ci/test/task-99"],
        fixture,
        { ...environment, RUNNER_DEBUG: "1" },
      );
      assertEquals(unknown.code, 1);
      assertStringIncludes(unknown.stderr, "Unknown task entrypoint");
      const unknownRecord = diagnosticRecord(unknown.stderr);
      assert(unknownRecord !== undefined);
      assertEquals(
        unknownRecord.operations[0].errorType,
        "entrypoint_not_found",
      );
    } finally {
      await Deno.remove(fixture, { recursive: true });
    }
  },
});

Deno.test({
  name: "artifact key uses repository-local source and explicit cache version",
  sanitizeOps: false,
  sanitizeResources: false,
  fn: async () => {
    const repositoryRoot = Deno.cwd();
    const fixture = await Deno.makeTempDir({ prefix: "tsugiori-key-" });
    const external = await Deno.makeTempDir({ prefix: "tsugiori-external-" });
    let remoteSource = 'export const remoteMarker = "first";\n';
    const server = Deno.serve(
      { hostname: "127.0.0.1", port: 0, onListen: () => {} },
      () =>
        new Response(remoteSource, {
          headers: { "content-type": "application/typescript" },
        }),
    );
    try {
      const coreModule = pathToFileURL(
        resolve(repositoryRoot, "packages/core/src/github_actions/mod.ts"),
      ).href;
      const externalModule = resolve(external, "dependency.ts");
      const externalUrl = pathToFileURL(externalModule).href;
      const remoteUrl = `http://127.0.0.1:${server.addr.port}/dependency.ts`;
      await Deno.writeTextFile(
        resolve(fixture, "deno.json"),
        `${
          JSON.stringify(
            {
              lock: false,
              imports: {
                "@atty303/tsugiori/github-actions": coreModule,
                "@atty303/tsugiori/run": pathToFileURL(
                  resolve(repositoryRoot, "packages/runner/src/main.ts"),
                ).href,
                "@std/yaml": "jsr:@std/yaml@^1.2.0",
              },
            },
            null,
            2,
          )
        }\n`,
      );
      await Deno.writeTextFile(
        externalModule,
        'export const cacheVersion = 1;\nexport const externalMarker = "first";\n',
      );
      const configSource =
        `import { defineTsugiori, pipeline } from "@atty303/tsugiori/github-actions";
import { runTsugiori } from "@atty303/tsugiori/run";
import { cacheVersion, externalMarker } from ${JSON.stringify(externalUrl)};
import { remoteMarker } from ${JSON.stringify(remoteUrl)};
void externalMarker;
void remoteMarker;
const ci = pipeline("ci", {
  output: ".github/workflows/ci.yml",
  events: ["push"],
}).job("test", ({ job }) =>
  job.runsOn("ubuntu-latest").task({ name: "Test", task: () => {} })
);
const config = defineTsugiori({ cacheVersion, pipelines: [ci] });
export default config;
if (import.meta.main) Deno.exitCode = await runTsugiori({ config, configUrl: import.meta.url, root: new URL("./", import.meta.url) });
`;
      await Deno.writeTextFile(resolve(fixture, "tsugiori.ts"), configSource);

      const firstDenoDirectory = resolve(fixture, "deno-cache-first");
      const secondDenoDirectory = resolve(fixture, "deno-cache-second");
      const baseline = await resolveSourceArtifactKey(
        fixture,
        firstDenoDirectory,
      );

      remoteSource = 'export const remoteMarker = "second";\n';
      const remoteChanged = await resolveSourceArtifactKey(
        fixture,
        secondDenoDirectory,
      );
      assertEquals(remoteChanged, baseline);

      await Deno.writeTextFile(
        externalModule,
        'export const cacheVersion = 1;\nexport const externalMarker = "second";\n',
      );
      const externalChanged = await resolveSourceArtifactKey(
        fixture,
        secondDenoDirectory,
      );
      assertEquals(externalChanged, baseline);

      await Deno.writeTextFile(
        externalModule,
        'export const cacheVersion = 2;\nexport const externalMarker = "second";\n',
      );
      const cacheVersionChanged = await resolveSourceArtifactKey(
        fixture,
        secondDenoDirectory,
      );
      assert(cacheVersionChanged !== baseline);

      await Deno.writeTextFile(
        externalModule,
        'export const cacheVersion = 1;\nexport const externalMarker = "second";\n',
      );
      await Deno.writeTextFile(
        resolve(fixture, "tsugiori.ts"),
        `${configSource}\n// repository-local source edit\n`,
      );
      const localSourceChanged = await resolveSourceArtifactKey(
        fixture,
        secondDenoDirectory,
      );
      assert(localSourceChanged !== baseline);

      await Deno.writeTextFile(resolve(fixture, "tsugiori.ts"), configSource);
      const targetChanged = await resolveSourceArtifactKey(
        fixture,
        secondDenoDirectory,
        Deno.build.target === "x86_64-unknown-linux-gnu"
          ? "aarch64-apple-darwin"
          : "x86_64-unknown-linux-gnu",
      );
      assert(targetChanged !== baseline);
    } finally {
      await server.shutdown();
      await Deno.remove(fixture, { recursive: true });
      await Deno.remove(external, { recursive: true });
    }
  },
});

Deno.test({
  name:
    "nested workflow project resolves one package for generation and artifact preparation",
  sanitizeOps: false,
  sanitizeResources: false,
  fn: async () => {
    const repositoryRoot = Deno.cwd();
    const fixture = await Deno.makeTempDir({ prefix: "tsugiori-nested-" });
    const project = resolve(fixture, "ci/pipelines");
    try {
      await copyDirectory(
        resolve(repositoryRoot, "packages"),
        resolve(fixture, "packages"),
      );
      const rootConfig = JSON.parse(
        await Deno.readTextFile(resolve(repositoryRoot, "deno.json")),
      ) as Record<string, unknown>;
      rootConfig.workspace = ["ci/pipelines"];
      await Deno.writeTextFile(
        resolve(fixture, "deno.json"),
        JSON.stringify(rootConfig),
      );
      await Deno.copyFile(
        resolve(repositoryRoot, "deno.lock"),
        resolve(fixture, "deno.lock"),
      );
      await Deno.mkdir(project, { recursive: true });
      await Deno.writeTextFile(
        resolve(project, "deno.json"),
        JSON.stringify({
          imports: {
            "@atty303/tsugiori": "workspace:*",
            "consumer-only": "./consumer-only.ts",
          },
          tasks: {
            generate: "deno run --frozen=true -A ./tsugiori.ts generate",
            "generate:check":
              "deno run --frozen=true -A ./tsugiori.ts generate --check",
          },
        }),
      );
      await Deno.writeTextFile(
        resolve(project, "consumer-only.ts"),
        "export const consumerMarker = true;\n",
      );
      await Deno.writeTextFile(
        resolve(project, "tsugiori.ts"),
        `import { consumerMarker } from "consumer-only";
void consumerMarker;
import { defineTsugiori, pipeline } from "@atty303/tsugiori/github-actions";
import { runTsugiori } from "@atty303/tsugiori/run";
const config = defineTsugiori({ pipelines: [pipeline("ci", {
  output: ".github/workflows/ci.yml", events: ["push"],
}).job("test", ({ job }) => job.runsOn("ubuntu-latest").task({
  name: "Test", task: () => {},
}))] });
export default config;
if (import.meta.main) Deno.exitCode = await runTsugiori({ config, configUrl: import.meta.url, root: new URL("../../", import.meta.url) });\n`,
      );
      const environment = Deno.env.toObject();
      const generated = await run(
        Deno.execPath(),
        ["task", "generate"],
        project,
        environment,
      );
      assertEquals(generated.code, 0, generated.stderr);
      const checked = await run(
        Deno.execPath(),
        ["task", "generate:check"],
        project,
        environment,
      );
      assertEquals(checked.code, 0, checked.stderr);
      const workflow = await Deno.readTextFile(
        resolve(fixture, ".github/workflows/ci.yml"),
      );
      assertStringIncludes(workflow, "working-directory: ci/pipelines");
      assertStringIncludes(workflow, "./tsugiori.ts");
      const expectedLayout = workflow.match(/ci\/test=sha256:[0-9a-f]+/)?.[0];
      assert(expectedLayout !== undefined);
      const githubOutput = resolve(fixture, "github-output");
      await Deno.writeTextFile(githubOutput, "");
      const resolved = await run(
        Deno.execPath(),
        [
          "run",
          "--frozen=true",
          "-A",
          "./tsugiori.ts",
          "github-actions",
          "task",
          "cache-key",
          "--expect-layout",
          expectedLayout,
        ],
        project,
        { ...environment, GITHUB_OUTPUT: githubOutput },
      );
      assertEquals(resolved.code, 0, resolved.stderr);
      const artifactKey = parseGitHubOutputs(
        await Deno.readTextFile(githubOutput),
      )["artifact-key"];
      assert(artifactKey !== undefined);
      await Deno.writeTextFile(githubOutput, "");
      const prepared = await run(
        Deno.execPath(),
        [
          "run",
          "--frozen=true",
          "-A",
          "./tsugiori.ts",
          "github-actions",
          "task",
          "prepare",
          "--expect-layout",
          expectedLayout,
          "--expected-key",
          artifactKey,
        ],
        project,
        { ...environment, GITHUB_OUTPUT: githubOutput },
      );
      assertEquals(prepared.code, 0, prepared.stderr);
      assertEquals(
        parseGitHubOutputs(
          await Deno.readTextFile(githubOutput),
        )["cache-write-required"],
        "true",
      );
      assertEquals(
        (await Deno.stat(resolve(fixture, ".tsugiori/task-runtime"))).isFile,
        true,
      );
    } finally {
      await Deno.remove(fixture, { recursive: true });
    }
  },
});

async function resolveSourceArtifactKey(
  fixture: string,
  denoDirectory: string,
  target?: string,
): Promise<string> {
  const output = resolve(fixture, `github-output-${crypto.randomUUID()}`);
  await Deno.writeTextFile(output, "");
  const result = await run(
    Deno.execPath(),
    [
      "run",
      "-A",
      "--frozen=true",
      "./tsugiori.ts",
      "github-actions",
      "task",
      "cache-key",
      ...(target === undefined ? [] : ["--target", target]),
    ],
    fixture,
    {
      ...Deno.env.toObject(),
      DENO_DIR: denoDirectory,
      GITHUB_OUTPUT: output,
    },
  );
  assertEquals(result.code, 0, result.stderr);
  const artifactKey = parseGitHubOutputs(await Deno.readTextFile(output))[
    "artifact-key"
  ];
  assert(artifactKey !== undefined);
  return artifactKey;
}

async function runTsugiori(
  args: readonly string[],
  fixture: string,
  env: Readonly<Record<string, string>>,
): Promise<Readonly<{ code: number; stdout: string; stderr: string }>> {
  return await run(
    Deno.execPath(),
    ["run", "--frozen=true", "-A", "./tsugiori.ts", ...args],
    resolve(fixture, ".github"),
    env,
  );
}

async function run(
  command: string,
  args: readonly string[],
  cwd: string,
  env: Readonly<Record<string, string>>,
): Promise<Readonly<{ code: number; stdout: string; stderr: string }>> {
  const result = await new Deno.Command(command, {
    args: [...args],
    cwd,
    env: { ...env },
    clearEnv: true,
    stdout: "piped",
    stderr: "piped",
  }).output();
  return {
    code: result.code,
    stdout: new TextDecoder().decode(result.stdout),
    stderr: new TextDecoder().decode(result.stderr),
  };
}

type DiagnosticRecord = Readonly<{
  status: "error" | "success";
  completeness: "complete" | "partial";
  operations: readonly Readonly<{
    name: string;
    status: "error" | "success";
    errorType?: string;
    attributes?: Readonly<Record<string, string>>;
  }>[];
}>;

function diagnosticRecord(stderr: string): DiagnosticRecord | undefined {
  return diagnosticRecords(stderr)[0];
}

function diagnosticRecords(stderr: string): readonly DiagnosticRecord[] {
  const records: DiagnosticRecord[] = [];
  for (const line of stderr.split("\n")) {
    if (!line.startsWith('{"schemaVersion":1,')) continue;
    records.push(JSON.parse(line) as DiagnosticRecord);
  }
  return records;
}

function parseGitHubOutputs(content: string): Readonly<Record<string, string>> {
  return Object.fromEntries(
    content.trim().split("\n").filter((line) => line.length > 0).map((line) => {
      const separator = line.indexOf("=");
      return [line.slice(0, separator), line.slice(separator + 1)];
    }),
  );
}

async function copyDirectory(
  source: string,
  destination: string,
): Promise<void> {
  await Deno.mkdir(destination, { recursive: true });
  for await (const entry of Deno.readDir(source)) {
    const from = resolve(source, entry.name);
    const to = resolve(destination, entry.name);
    if (entry.isDirectory) await copyDirectory(from, to);
    else if (entry.isFile) await Deno.copyFile(from, to);
  }
}
