import { extname, join, relative, resolve, sep } from "node:path";
import { type GeneratedFile, generatedWorkflowHeader } from "./generator.ts";
import { resolveGeneratedDestinations } from "./write.ts";

export type StaleGeneratedFile = Readonly<{
  path: string;
  reason: "missing" | "changed" | "extra";
}>;

export async function checkGeneratedFiles(
  rootDirectory: string,
  configArgument: string,
  files: readonly GeneratedFile[],
  selectedOutput?: string,
): Promise<readonly StaleGeneratedFile[]> {
  const destinations = resolveGeneratedDestinations(rootDirectory, files);
  const owner = configArgument.replace(/^\.\//, "");
  const selected = selectedOutput === undefined
    ? undefined
    : resolveGeneratedDestinations(rootDirectory, [{
      path: selectedOutput,
      content: "",
    }])[0].output;
  const expected = new Map(
    destinations.map(({ file, output }) => [output, file]),
  );
  const checked = selected === undefined
    ? destinations
    : destinations.filter(({ output }) => output === selected);
  const stale: StaleGeneratedFile[] = [];

  for (const { file, output } of checked) {
    const actual = await readIfPresent(output);
    if (actual === undefined) {
      stale.push({
        path: displayPath(rootDirectory, output),
        reason: "missing",
      });
    } else if (!sameBytes(actual, new TextEncoder().encode(file.content))) {
      stale.push({
        path: displayPath(rootDirectory, output),
        reason: "changed",
      });
    }
  }

  if (selected !== undefined) {
    if (!expected.has(selected)) {
      const actual = await readIfPresent(selected);
      if (actual !== undefined && ownedBy(actual, configArgument)) {
        stale.push({
          path: displayPath(rootDirectory, selected),
          reason: "extra",
        });
      } else {
        throw new Error(
          `Workflow output is not generated by ${owner}: ${
            displayPath(rootDirectory, selected)
          }`,
        );
      }
    }
  } else {
    const workflowRoot = resolve(rootDirectory, ".github/workflows");
    for (const output of await workflowFiles(workflowRoot)) {
      if (expected.has(output)) continue;
      const actual = await Deno.readFile(output);
      if (ownedBy(actual, configArgument)) {
        stale.push({
          path: displayPath(rootDirectory, output),
          reason: "extra",
        });
      }
    }
  }
  return stale.sort((left, right) => left.path.localeCompare(right.path));
}

function displayPath(rootDirectory: string, output: string): string {
  return relative(rootDirectory, output).split(sep).join("/");
}

async function readIfPresent(path: string): Promise<Uint8Array | undefined> {
  try {
    return await Deno.readFile(path);
  } catch (error) {
    if (error instanceof Deno.errors.NotFound) return undefined;
    throw error;
  }
}

async function workflowFiles(directory: string): Promise<string[]> {
  const files: string[] = [];
  try {
    for await (const entry of Deno.readDir(directory)) {
      const path = join(directory, entry.name);
      if (entry.isDirectory) files.push(...await workflowFiles(path));
      else if (entry.isFile && extname(path) === ".yml") files.push(path);
    }
  } catch (error) {
    if (!(error instanceof Deno.errors.NotFound)) throw error;
  }
  return files;
}

function ownedBy(content: Uint8Array, configArgument: string): boolean {
  const header = new TextEncoder().encode(
    generatedWorkflowHeader(configArgument),
  );
  return content.length >= header.length &&
    header.every((byte, index) => content[index] === byte);
}

function sameBytes(left: Uint8Array, right: Uint8Array): boolean {
  return left.length === right.length &&
    left.every((byte, index) => byte === right[index]);
}
