import { resolveProjectWorkingDirectory } from "./source.ts";
import type { DiagnosticRecorder } from "../task-runtime/diagnostics.ts";
import { posix } from "node:path";
import { actionPayload } from "./action_payload.ts";
import { emitCompositeAction } from "./github_actions/action.ts";
import { TASK_PREPARE_SCRIPT } from "../task-runtime/bootstrap.ts";
import type { ProjectConfig } from "../github_actions/mod.ts";
import { taskPrepareAction } from "../package_identity.ts";
import { AuthoringValidationError, lowerProject } from "./authoring.ts";
import { emitWorkflow } from "./github_actions/emitter.ts";

export type GeneratedFile = Readonly<{
  path: string;
  content: string | Uint8Array;
}>;

export function generatedWorkflowHeader(entrypointArgument: string): string {
  return `# Generated by Tsugiori from ${
    entrypointArgument.replace(/^\.\//, "")
  }\n`;
}

export async function generateFiles(
  project: ProjectConfig,
  entrypointArgument: string,
  sourceKey: string,
  options: Readonly<{
    projectDirectory?: string;
    recorder?: DiagnosticRecorder;
  }> = {},
): Promise<readonly GeneratedFile[]> {
  const projectDirectory = options.projectDirectory ?? Deno.cwd();
  const workingDirectory = await resolveProjectWorkingDirectory(
    project,
    projectDirectory,
    options.recorder,
  );
  const lowered = lowerProject(
    project,
    entrypointArgument,
    sourceKey,
    false,
    workingDirectory,
  );
  if (
    project.workflows.some((workflow) =>
      workflow.jobs.some((job) =>
        job.steps.some((step) => step.type === "task")
      )
    ) &&
    taskPrepareAction(project.localTaskPrepareAction) === undefined
  ) {
    throw new AuthoringValidationError([
      "Task preparation requires a released Tsugiori package with a source commit SHA, or an explicit localTaskPrepareAction checkout path for development.",
    ]);
  }
  const files: GeneratedFile[] = lowered.workflows.map((workflow) => ({
    path: workflow.path,
    content: generatedWorkflowHeader(entrypointArgument) +
      emitWorkflow(workflow.workflow),
  }));
  const hasActionTasks = lowered.actions.some(({ action }) =>
    action.runs.steps.some((step) => step.type === "task")
  );
  const payload = hasActionTasks
    ? await actionPayload(
      projectDirectory,
      entrypointArgument,
      project.cacheVersion,
    )
    : undefined;
  for (const action of lowered.actions) {
    const needsPayload = action.action.runs.steps.some((step) =>
      step.type === "task"
    );
    files.push({
      path: action.action.path,
      content: generatedWorkflowHeader(entrypointArgument) +
        emitCompositeAction(action, needsPayload ? payload : undefined),
    });
    if (needsPayload && payload) {
      files.push(
        ...payload.files.map((file) => ({
          ...file,
          path: posix.join(
            posix.dirname(action.action.path),
            ".tsugiori",
            file.path,
          ),
        })),
      );
      files.push({
        path: posix.join(
          posix.dirname(action.action.path),
          ".tsugiori/prepare.sh",
        ),
        content: TASK_PREPARE_SCRIPT,
      });
    }
  }
  return files;
}
