import type { ProjectConfig } from "../github_actions/mod.ts";
import { lowerProject } from "./authoring.ts";
import { emitWorkflow } from "./github_actions/emitter.ts";

export type GeneratedFile = Readonly<{
  path: string;
  content: string;
}>;

export function generatedWorkflowHeader(entrypointArgument: string): string {
  return `# Generated by Tsugiori from ${
    entrypointArgument.replace(/^\.\//, "")
  }\n`;
}

export async function generateFiles(
  project: ProjectConfig,
  entrypointArgument: string,
): Promise<readonly GeneratedFile[]> {
  const lowered = await lowerProject(project, entrypointArgument);
  return lowered.workflows.map((workflow) => ({
    path: workflow.path,
    content: generatedWorkflowHeader(entrypointArgument) +
      emitWorkflow(workflow.workflow),
  }));
}
