import type { TsugioriConfig } from "../../core/src/mod.ts";
import { lowerConfig } from "./authoring.ts";
import { emitWorkflow } from "./github_actions/emitter.ts";

export type GeneratedFile = Readonly<{
  path: string;
  content: string;
}>;

export function generatedWorkflowHeader(configArgument: string): string {
  return `# Generated by Tsugiori from ${
    configArgument.replace(/^\.\//, "")
  }\n`;
}

export async function generateFiles(
  config: TsugioriConfig,
  configArgument: string,
  projectArgument: string,
): Promise<readonly GeneratedFile[]> {
  const lowered = await lowerConfig(config, configArgument, projectArgument);
  return lowered.pipelines.map((pipeline) => ({
    path: pipeline.output,
    content: generatedWorkflowHeader(configArgument) +
      emitWorkflow(pipeline.workflow),
  }));
}
